### ISSUE TITLE
Type not updated after disconnecting argument

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/Groep10#84]
When a block is connected, types seem to be updated correctly. Disconnecting a block only seems to update the block the connection was modified on, leaving blocks lower in the hierarchy in a wrong state.

![bug](https://cloud.githubusercontent.com/assets/126832/7555611/086dd148-f751-11e4-87ab-d5bc81ab48cf.png)

`const` argument (and result) doesn't go back to being unconstrained after being disconnected. This seems to be a regression introduced by #82.

**Comment by i3anaan** [comment]
Waar denk je dat dit probleem zit?

**Comment by i3anaan** [comment]
Zou iets kunnen zijn met het invalidaten

**Comment by wandernauta** [comment]
Jup. Kan het niet reproduceren met een commit van vóór 82.

**Comment by wandernauta** [comment]
Volgens `git bisect` is het probleem geintroduceerd in [deze commit](https://github.com/wandernauta/Groep10/commit/85f622ba5c7d9bff225f80316386c2b54bca3858), dus de eerste commit waarin we niet voor elk blok invalidate aanroepen.

**Comment by i3anaan** [comment]
Heb het probleem gevonden, iets deed een normale invalidate ipv een cascading.
Er lijkt nog een verdubbeling in te zitten, dit ga ik ook nog even bekijken voordat ik een fix indien

**Comment by i3anaan** [comment]
Dat lijkt gelijk opgelost te zijn, ik zal pr indienen

**Comment by i3anaan** [comment]
Heb pr ingediend: #86

**Comment by wandernauta** [comment]
Issue lijkt gefixt te zijn. Thanks.
